### PR TITLE
updating dropdown styles to match spec and adding checkbox mode to demo

### PR DESCRIPTION
**Pull request by arcpato**
- Updated default dropdown styles to match the px spec
From this:
screen shot 2016-12-19 at 1 07 00 pm

To this:
screen shot 2016-12-19 at 1 08 39 pm

Spec:
screen shot 2016-12-16 at 10 20 15 am

- Updated the disabled dropdown styles to match the spec 
From this:
screen shot 2016-12-19 at 1 07 05 pm

To this:
screen shot 2016-12-19 at 1 08 00 pm

- Added checkboxes mode to demo as it was missing
screen shot 2016-12-19 at 1 07 18 pm

Might want to have Wade, Hans and Rob to take a look. @runn-vermel  @randyaskin

### CODE REVIEW

**Comment by runn-vermel** [comment]
I'm waiting on Design feedback before I merge this in.

**Comment by arcpato** [comment]
Did design review?

**Comment by runn-vermel** [comment]
Thanks for the PR, @arcpato ! this was accepted, and is available in v2.1.2

**Comment by mdwragg** [comment]
@arcpato @runn-vermel this has caused issues, see #21

**Comment by arcpato** [comment]
Ah, sorry about that. Here's a PR to fix that https://github.com/PredixDev/px-dropdown/pull/23, unless you want to revert.

**Pull request merged**
