### PR TITLE
new search / filtering capability for px-dropdown

### PR DESCRIPTION
**Pull request by budsalvetti**
# Pull Request

Hi,

Thanks for helping us improve the Predix UI platform by submitting a Pull Request.

To help us merge your Pull Request as fast as possible, please fill out the following sections:

* ## A description of the changes proposed in the pull request:

* ## A reference to a related issue (if applicable):

* ## @mentions of the person or team responsible for reviewing proposed changes:

* ## working tests:

### CODE REVIEW

**Comment by PiotrekPaprocki** [comment]
Why it wasn't merged, any explanation? I did check @budsalvetti branch and it looks fine. I'm about to implement kinda behavior in my app and i was considering contribute to px-dropdown, but I see it's already done.

**Comment by randyaskin** [comment]
@PiotrekPaprocki I'm not sure, maybe the team didn't need it anymore? I tried to check it out, but our team is currently making changes to the way the demo pages work and the px-dropdown-content-demo.html page hasn't been migrated yet, so I wasn't able to get it working in my local. Will take a look when I can.

**Comment by PiotrekPaprocki** [comment]
@randyaskin I've seen they've made some changes recently, because I forked the repo few days ago and now I have to rewrite a bit. Do you know how long it's gonna take and are they going to update px-dropdown-content.html as well? Because I've implemented some features there and I don't know if should I create a pull request or wait a few days for the update.

**Comment by runn-vermel** [comment]
Hi @PiotrekPaprocki - good news, should be done by EOD today :)

**Comment by budsalvetti** [comment]
hey do you work for GE?

**Comment by runn-vermel** [comment]
I do. otherwise, the optimistic comment above would be unrealistic :)

**Comment by PiotrekPaprocki** [comment]
@runn-vermel Awesome:) I'll pull the changes next week and work on my update.

**Comment by sumeet-singh04** [comment]
@runn-vermel @PiotrekPaprocki  What is this pr about ? Does this relate to #30 ?

**Comment by runn-vermel** [comment]
@sumeet-singh04 - it does not.
@PiotrekPaprocki  - this is fixed in version 2.2.7

**Comment by gitclouddeveloper** [comment]
@runn-vermel I tried pulling the latest commit of this pull request but it did not work as per the PX-Dropdown-Content-Demo.html functionality. Can you please let me know, whether there is any other changes pending from your end or can I get it from the latest PX-Dropdown branch?

**Comment by runn-vermel** [comment]
Hi @gitclouddeveloper - this pull request was never pulled in, which is why this isn't working as advertised ;)

**Pull request closed without merging**
